services:
  graphitestatsd:
    image: graphiteapp/graphite-statsd
    expose:
      - 80
      - 8125/udp
    ports:
      - 8080:80

  nsqlookupd:
    image: nsqio/nsq:v1.2.1
    command: /nsqlookupd
    expose:
      - 4160
      - 4161
    ports:
      - 4161:4161
  nsqd:
    image: nsqio/nsq:v1.2.1
    volumes:
      - /data
    command: "sh -c '/nsqd \
      -broadcast-address=localhost \
      -data-path=/data \
      -lookupd-tcp-address=nsqlookupd:4160 \
      -e2e-processing-latency-percentile=1.0,0.99,0.95,0.70 \
      -statsd-address=graphitestatsd:8125 \
      '"
    links:
      - nsqlookupd
      - graphitestatsd
    expose:
      - 4150
      - 4151
    ports:
      - 4150:4150
      - 4151:4151

  nsqadmin:
    image: nsqio/nsq:v1.2.1
    command: "sh -c '/nsqadmin \
      -lookupd-http-address=nsqlookupd:4161 \
      -graphite-url=http://grahitestatsd:8080 \
      -proxy-graphite \
      -statsd-counter-format=stats.%s \
      '"
    links:
      - nsqlookupd
      - nsqd
      - graphitestatsd
    expose:
      - 4171
    ports:
      - 4171:4171
